// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdminRecoveryRequest(arg1) {
  return window['go']['main']['App']['AdminRecoveryRequest'](arg1);
}

export function AdminRecoveryVerify(arg1, arg2, arg3) {
  return window['go']['main']['App']['AdminRecoveryVerify'](arg1, arg2, arg3);
}

export function BootstrapAdmin(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BootstrapAdmin'](arg1, arg2, arg3, arg4);
}

export function CreateAdminRequest(arg1) {
  return window['go']['main']['App']['CreateAdminRequest'](arg1);
}

export function CreateJobOption(arg1) {
  return window['go']['main']['App']['CreateJobOption'](arg1);
}

export function CreateJobTemplate(arg1) {
  return window['go']['main']['App']['CreateJobTemplate'](arg1);
}

export function CreateMember(arg1) {
  return window['go']['main']['App']['CreateMember'](arg1);
}

export function CreateTransaction(arg1) {
  return window['go']['main']['App']['CreateTransaction'](arg1);
}

export function DeleteJobOption(arg1) {
  return window['go']['main']['App']['DeleteJobOption'](arg1);
}

export function DeleteJobTemplate(arg1) {
  return window['go']['main']['App']['DeleteJobTemplate'](arg1);
}

export function DeleteMember(arg1) {
  return window['go']['main']['App']['DeleteMember'](arg1);
}

export function GetActiveJobTemplates() {
  return window['go']['main']['App']['GetActiveJobTemplates']();
}

export function GetAdminDashboardData(arg1) {
  return window['go']['main']['App']['GetAdminDashboardData'](arg1);
}

export function GetAllJobs() {
  return window['go']['main']['App']['GetAllJobs']();
}

export function GetAnalyticsData(arg1) {
  return window['go']['main']['App']['GetAnalyticsData'](arg1);
}

export function GetAuditLogs() {
  return window['go']['main']['App']['GetAuditLogs']();
}

export function GetAuditLogsDetailed(arg1) {
  return window['go']['main']['App']['GetAuditLogsDetailed'](arg1);
}

export function GetBootstrapStatus() {
  return window['go']['main']['App']['GetBootstrapStatus']();
}

export function GetMachineConfig() {
  return window['go']['main']['App']['GetMachineConfig']();
}

export function GetMembers() {
  return window['go']['main']['App']['GetMembers']();
}

export function GetMembersWithStats() {
  return window['go']['main']['App']['GetMembersWithStats']();
}

export function GetServerConfig() {
  return window['go']['main']['App']['GetServerConfig']();
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout(arg1) {
  return window['go']['main']['App']['Logout'](arg1);
}

export function ResetMemberPassword(arg1) {
  return window['go']['main']['App']['ResetMemberPassword'](arg1);
}

export function SecureMemberAction(arg1) {
  return window['go']['main']['App']['SecureMemberAction'](arg1);
}

export function SetMachineConfig(arg1) {
  return window['go']['main']['App']['SetMachineConfig'](arg1);
}

export function TestConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2, arg3);
}

export function UpdateJobOption(arg1) {
  return window['go']['main']['App']['UpdateJobOption'](arg1);
}

export function UpdateJobTemplate(arg1) {
  return window['go']['main']['App']['UpdateJobTemplate'](arg1);
}

export function UpdateMember(arg1) {
  return window['go']['main']['App']['UpdateMember'](arg1);
}

export function UpdateServerConfig(arg1) {
  return window['go']['main']['App']['UpdateServerConfig'](arg1);
}

export function VerifyAdminRequest(arg1) {
  return window['go']['main']['App']['VerifyAdminRequest'](arg1);
}
