// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {models} from '../models';

export function AdminRecoveryRequest(arg1:string):Promise<services.BasicResponse>;

export function AdminRecoveryVerify(arg1:string,arg2:string,arg3:string):Promise<services.BasicResponse>;

export function BootstrapAdmin(arg1:string,arg2:string,arg3:string,arg4:string):Promise<services.BasicResponse>;

export function CreateAdminRequest(arg1:services.CreateAdminRequestInput):Promise<services.CreateAdminRequestResponse>;

export function CreateJobOption(arg1:services.JobOptionRequest):Promise<services.BasicResponse>;

export function CreateJobTemplate(arg1:services.JobTemplateRequest):Promise<services.BasicResponse>;

export function CreateMember(arg1:services.MemberRequest):Promise<services.BasicResponse>;

export function CreateTransaction(arg1:services.CreateTransactionRequest):Promise<models.Transaction>;

export function DeleteJobOption(arg1:string):Promise<services.BasicResponse>;

export function DeleteJobTemplate(arg1:string):Promise<services.BasicResponse>;

export function DeleteMember(arg1:services.DeleteMemberRequest):Promise<services.BasicResponse>;

export function GetActiveJobTemplates():Promise<Array<models.JobTemplate>>;

export function GetAdminDashboardData(arg1:string):Promise<services.AdminDashboardData>;

export function GetAllJobs():Promise<Array<models.JobTemplate>>;

export function GetAnalyticsData(arg1:services.AnalyticsFilters):Promise<services.AnalyticsResponse>;

export function GetAuditLogs():Promise<Array<models.AuditLog>>;

export function GetAuditLogsDetailed(arg1:services.GetAuditLogsRequest):Promise<Array<services.AuditLogDetailed>>;

export function GetBootstrapStatus():Promise<services.BootstrapStatusResponse>;

export function GetMachineConfig():Promise<services.MachineConfig>;

export function GetMembers():Promise<Array<models.User>>;

export function GetMembersWithStats():Promise<Array<services.MemberWithStats>>;

export function GetServerConfig():Promise<models.ServerConfig>;

export function GetSession(arg1:string):Promise<services.AuthResponse>;

export function Greet(arg1:string):Promise<string>;

export function Login(arg1:string,arg2:string):Promise<services.AuthResponse>;

export function Logout(arg1:string):Promise<services.AuthResponse>;

export function ResetMemberPassword(arg1:services.ResetMemberPasswordRequest):Promise<services.BasicResponse>;

export function SecureMemberAction(arg1:services.SecureActionRequest):Promise<services.BasicResponse>;

export function SetMachineConfig(arg1:services.MachineConfig):Promise<services.BasicResponse>;

export function TestConnection(arg1:string,arg2:number,arg3:string):Promise<services.BasicResponse>;

export function UpdateJobOption(arg1:services.JobOptionRequest):Promise<services.BasicResponse>;

export function UpdateJobTemplate(arg1:services.JobTemplateRequest):Promise<services.BasicResponse>;

export function UpdateMember(arg1:services.MemberRequest):Promise<services.BasicResponse>;

export function UpdateServerConfig(arg1:services.UpdateServerConfigRequest):Promise<services.ServerConfigResponse>;

export function VerifyAdminRequest(arg1:services.VerifyAdminRequestInput):Promise<services.BasicResponse>;
