// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function GetSession(arg1:string):Promise<services.AuthResponse>;

export function Greet(arg1:string):Promise<string>;

export function Login(arg1:string,arg2:string):Promise<services.AuthResponse>;

export function Logout(arg1:string):Promise<services.AuthResponse>;
